version: '2'
services:
  zk:
      image: zookeeper:3.5
      network_mode: host
      restart: on-failure
      volumes:
        - /tmp/zk/data:/data:rw
        - /tmp/zk/datalog:/datalog:rw
      environment:
        ZOO_STANDALONE_ENABLED: "true"
  master:
    image: mesosphere/mesos-master:1.5.0
    network_mode: host
    restart: on-failure
    volumes:
      - /tmp/mesos/master/tmp:/var/tmp/mesos:rw
      - /tmp/mesos/master/log:/var/log/mesos:rw
    environment:
      MESOS_ZK: zk://127.0.0.1:2181/mesos
      MESOS_PORT: 5050
      MESOS_QUORUM: 1
      MESOS_REGISTRY: in_memory
      MESOS_LOG_DIR: /var/log/mesos
      MESOS_WORK_DIR: /var/tmp/mesos

  slave:
    image: mesosphere/mesos-slave:1.5.0
    network_mode: host
    privileged: true
    restart: on-failure
    volumes:
      - /tmp/mesos/slave/tmp:/var/tmp/mesos:rw
      - /tmp/mesos/slave/log:/var/log/mesos:rw
      - /cgroup:/cgroup:rw
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - /usr/local/bin/docker:/usr/local/bin/docker:ro
      - /sys:/sys:rw
      - /run/systemd/system:/run/systemd/system:rw
    command: mesos-agent --no-systemd_enable_support
    environment:
      MESOS_MASTER: zk://127.0.0.1:2181/mesos
      MESOS_PORT: 5051
      MESOS_SWITCH_USER: 0
      MESOS_CONTAINERIZERS: docker,mesos
      MESOS_LOG_DIR: /var/log/mesos
      MESOS_WORK_DIR: /var/tmp/mesos
      MESOS_NO_SYSTEMD_ENABLE_SUPPORT: 0

  marathon:
    image: mesosphere/marathon:v1.5.8
    network_mode: host
    restart: on-failure
    environment:
      MARATHON_MASTER: zk://127.0.0.1:2181/mesos
      MARATHON_ZK: zk://localhost:2181/marathon
      MARATHON_HTTP_PORT: 8081

  chronos:
    image: mesosphere/chronos:v3.0.2
    network_mode: host
    restart: on-failure
    command: --master zk://127.0.0.1:2181/mesos --zk_hosts zk://127.0.0.1:2181
    environment:
      CHRONOS_MASTER: zk://127.0.0.1:2181/mesos
      CHRONOS_ZK_HOSTS: zk://localhost:2181
      PORT0: 8082
      PORT1: 8083
      CHRONOS_WORK_DIR: /tmp
      MESOS_WORK_DIR: /tmp
      CHRONOS_MESOS_FRAMEWORK_NAME: chronos
      CHRONOS_HOSTNAME: localhost
